# CHANGE-TO-YOURNAME-aws-node-http-api-project to your repo name! in line 2, service.
service: 3-12-cdserverlessv2ec
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline