name: CICD for Serverless Application-title of action
run-name: ${{github.actor}} is doing CICD for serverless application

on: 
  push:
    branches: [ main, "*"]

jobs:
  pre-deploy:
    runs-on:ubuntu-lastest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event.name }} event."